# - Api Dopcumentaiton

# Get all items
# GET http://localhost:4000/items

# Get single item
# GET http://localhost:4000/items/1

# Add item
POST http://localhost:4000/item
Content-Type: application/json

{
  # "name": "Item"
}
